
services:

  frontend:
    image: YOUR_DOCKERHUB_USERNAME/amazona-frontend:latest
    container_name: amazona-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: YOUR_DOCKERHUB_USERNAME/amazona-backend:latest
    container_name: amazona-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URL: mongodb://mongodb:27017/amazona
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: amazona-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:

