export default {
  products: [
    {
      _id: '1',
      name: 'Slim Fit Oxford Cotton Shirt',
      category: 'Shirts',
      image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
      price: 69.99,
      brand: 'Ralph Lauren',
      rating: 4.8,
      numReviews: 24,
      countInStock: 15,
      description: 'Crafted from breathable 100% long-staple cotton, this tailored Oxford shirt delivers crisp style and all-day comfort for both formal and casual settings.',
    },
    {
      _id: '2',
      name: 'Casual Chambray Denim Shirt',
      category: 'Shirts',
      image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80',
      price: 54.99,
      brand: "Levi's",
      rating: 4.6,
      numReviews: 18,
      countInStock: 8,
      description: 'Soft-washed lightweight denim with a classic button-down collar, dual chest pockets, and durable contrast stitching.',
    },
    {
      _id: '3',
      name: 'Urban Classic Chino Pants',
      category: 'Pants',
      image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&auto=format&fit=crop&q=80',
      price: 79.99,
      brand: 'Tommy Hilfiger',
      rating: 4.7,
      numReviews: 32,
      countInStock: 12,
      description: 'Versatile slim-fit stretch chinos featuring moisture-wicking technology, reinforced pocket linings, and modern taper.',
    },
    {
      _id: '4',
      name: 'Slim Stretch Denim Jeans',
      category: 'Pants',
      image: 'https://images.unsplash.com/photo-1542272604-780c96856453?w=600&auto=format&fit=crop&q=80',
      price: 89.99,
      brand: "Levi's",
      rating: 4.9,
      numReviews: 45,
      countInStock: 20,
      description: 'Timeless 5-pocket styling engineered with premium flexible denim for maximum mobility and enduring shape retention.',
    },
    {
      _id: '5',
      name: 'Pro Wireless Noise-Cancelling Headphones',
      category: 'Electronics',
      image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
      price: 199.99,
      brand: 'Sony',
      rating: 4.9,
      numReviews: 58,
      countInStock: 10,
      description: 'Industry-leading active noise cancellation, 30-hour battery life, high-resolution audio codecs, and plush memory-foam earcups.',
    },
    {
      _id: '6',
      name: 'Smart Fitness Watch Series 7',
      category: 'Electronics',
      image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
      price: 299.99,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 72,
      countInStock: 14,
      description: 'Always-On Retina display with ECG, blood oxygen monitoring, multi-sport GPS tracking, and 50m water resistance.',
    },
    {
      _id: '7',
      name: 'Air Cushion Running Sneakers',
      category: 'Footwear',
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
      price: 129.99,
      brand: 'Nike',
      rating: 4.9,
      numReviews: 94,
      countInStock: 18,
      description: 'Ultra-lightweight mesh upper combined with responsive air cushioning system for explosive energy return on every stride.',
    },
    {
      _id: '8',
      name: 'Leather Minimalist Dress Shoes',
      category: 'Footwear',
      image: 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=600&auto=format&fit=crop&q=80',
      price: 119.99,
      brand: 'Clarks',
      rating: 4.7,
      numReviews: 29,
      countInStock: 7,
      description: 'Handcrafted full-grain calfskin leather shoes with cushioned OrthoLite insoles and Goodyear-welted rubber soles.',
    },
    {
      _id: '9',
      name: 'Genuine Vintage Leather Jacket',
      category: 'Fashion',
      image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
      price: 189.99,
      brand: 'Zara',
      rating: 4.8,
      numReviews: 38,
      countInStock: 5,
      description: 'Supple lambskin leather jacket with asymmetrical moto zipper, quilted shoulder accents, and thermal quilted inner lining.',
    },
    {
      _id: '10',
      name: 'Premium Heavyweight Fleece Hoodie',
      category: 'Fashion',
      image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80',
      price: 64.99,
      brand: 'Champion',
      rating: 4.6,
      numReviews: 51,
      countInStock: 25,
      description: 'Double-stitched 450GSM reverse-weave fleece engineered to resist vertical shrinkage, with kangaroo pocket and ribbed cuffs.',
    },
    {
      _id: '11',
      name: 'Aviator Polarized Sunglasses',
      category: 'Accessories',
      image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80',
      price: 149.99,
      brand: 'Ray-Ban',
      rating: 4.9,
      numReviews: 63,
      countInStock: 15,
      description: 'Iconic crystal green polarized G-15 lenses housed in lightweight metal gold frames offering 100% UV400 protection.',
    },
    {
      _id: '12',
      name: 'Water-Resistant Commuter Backpack',
      category: 'Accessories',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
      price: 84.99,
      brand: 'Herschel',
      rating: 4.8,
      numReviews: 41,
      countInStock: 16,
      description: 'Durable Cordura ballistic nylon with dedicated padded 16-inch laptop compartment, hidden passport pocket, and luggage strap.',
    },
  ],
};